spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://sicmdbinstance.cjbecpipb7jm.ap-northeast-2.rds.amazonaws.com:3306/techdomdb
    username: techdom
    password: techdom!@